// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlFahwKe5T1g5VDeeBtnyVY2x4QVavbaU',
    appId: '1:660382727156:android:c3b62fa8b808cd2b2357a1',
    messagingSenderId: '660382727156',
    projectId: 'napurisapuska',
    storageBucket: 'napurisapuska.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmwiZQqCwnfBb5pjgYM39eR75qAJvgtkA',
    appId: '1:660382727156:web:672e9a08566f22192357a1',
    messagingSenderId: '660382727156',
    projectId: 'napurisapuska',
    authDomain: 'napurisapuska.firebaseapp.com',
    storageBucket: 'napurisapuska.firebasestorage.app',
    measurementId: 'G-SQQNK649L1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI4HNz-Dq8CIDlw2xhtFmwVDwfALcuHCo',
    appId: '1:660382727156:ios:698a8f8df80ac8e52357a1',
    messagingSenderId: '660382727156',
    projectId: 'napurisapuska',
    storageBucket: 'napurisapuska.firebasestorage.app',
    iosBundleId: 'com.napurisapuska.fi',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI4HNz-Dq8CIDlw2xhtFmwVDwfALcuHCo',
    appId: '1:660382727156:ios:698a8f8df80ac8e52357a1',
    messagingSenderId: '660382727156',
    projectId: 'napurisapuska',
    storageBucket: 'napurisapuska.firebasestorage.app',
    iosBundleId: 'com.napurisapuska.fi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmwiZQqCwnfBb5pjgYM39eR75qAJvgtkA',
    appId: '1:660382727156:web:77ce3a879cbeb0f52357a1',
    messagingSenderId: '660382727156',
    projectId: 'napurisapuska',
    authDomain: 'napurisapuska.firebaseapp.com',
    storageBucket: 'napurisapuska.firebasestorage.app',
    measurementId: 'G-YRL9EFSKZX',
  );
}
